name: Deploy Nextcloud to EC2

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"

jobs:
  deploy:
    name: Deploy Nextcloud
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Copy Docker Compose files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r apps/ ubuntu@${{ vars.BASTION_HOST }}:~/

    - name: SSH into Bastion Host and Deploy to Private EC2
      env:
        EC2_USER: ${{ vars.EC2_USER }}
        EC2_HOST: ${{ vars.EC2_HOST }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        POSTGRES_USER: ${{ vars.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        NEXTCLOUD_ADMIN_USER: ${{ vars.NEXTCLOUD_ADMIN_USER }}
        NEXTCLOUD_ADMIN_PASSWORD: ${{ secrets.NEXTCLOUD_ADMIN_PASSWORD }}
        EC2_PUBLIC_IP: ${{ vars.EC2_PUBLIC_IP }}
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ vars.BASTION_HOST }}
        username: ${{ vars.BASTION_USER }} 
        key: ${{ secrets.BASTION_PRIVATE_KEY }}
        port: 22
        script: |
          scp -o StrictHostKeyChecking=no -i .ssh/wp_server_keypair_private_key.pem -r ~/wordpress vars.EC2_USER@${{ vars.EC2_HOST }}:~/
          # SSH to the private EC2 instance from the bastion host
          ssh -o StrictHostKeyChecking=no -T -i .ssh/wp_server_keypair_private_key.pem vars.EC2_USER@${{ vars.EC2_HOST }} << 'EOF'
            # Deploy Docker Compose files directly from the repo
            ls
            cd ~/apps
            echo POSTGRES_USER=${POSTGRES_USER} >> .env
            echo POSTGRES_PASSWORD=${POSTGRES_PASSWORD} >> .env
            echo REDIS_PASSWORD=${REDIS_PASSWORD} >> .env
            echo NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER} >> .env
            echo NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD} >> .env
            echo EC2_PUBLIC_IP=${EC2_PUBLIC_IP} >> .env
            docker compose up -d
            docker ps
          EOF
